### ISSUE TITLE
Payment methode

### ISSUE THREAD

**Issue by teletobbie** [woesterduolf/Mission-reisbureau#30]
**Mockup design (see page 7)**

The main area is the payment area. On top we still have the booking plus the booking number.
The customer is greeted with the question which method of payment he would like to use. He can then select that payment option from a dropdown menu displaying all the possible options.
Once he has selected the payment option, the customer has to fill in a form.

The top part of the form is asking the customer to enter the name of the accountholder for the selected payment option. He can then fill in his name in the field.
Below that, the customer is asked to put in the card number for his selected payment option. He can then fill in his number in the field.

After that we have text asking the customer to fil in the security number of his card. This is displayed on the back of his card most of the time. He can then fill in the number in the field.
Lastly we have 2 times an area where the customer is asked for his address info. He can put in the address info in the respective fields. 

Once all has been filled in , he can click the ‘confirm payment’  button, which will make the back process the payment information. The customer will be taken to the booking confirmation page if the payment was successful. If it wasn’t, he will get an error screen. 
And last, in the bottom right corner are all the payment methods shown with their own logos. This makes it a bit easier to see if your payment method is accepted.

**Comment by woesterudolf** [comment]
Eerste opzet gemaakt
